name: nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Build
      uses: actions/cache@v2
      with:
        path: |
          *.build
        key: ${{ runner.os }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install httpie nuitka
    - name: Run nuitka
      run: |
        python -m nuitka --standalone --show-scons --show-progress --assume-yes-for-downloads -o http httpie.py
    - uses: actions/upload-artifact@v2
      with:
        name: httpie
        path: "*.dist"
